/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List products (paginated + filters) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              products: {
                name: string;
                /** @default  */
                description: string;
                price: number;
                /** @default 0 */
                discount: number;
                /** @default false */
                stock: boolean;
                /** @default  */
                category: string;
                /** @default  */
                image_path: string;
                /** @default  */
                image_avif_path: string;
                /** @default 0 */
                order: number;
                /** @default false */
                is_archived: boolean;
                /** @default 0 */
                rev: number;
                /** @default {} */
                field_last_modified: {
                  [key: string]: {
                    ts?: string;
                    by?: string;
                    rev?: number;
                    base_rev?: number;
                    changeset_id?: string | null;
                  };
                };
                id?: string;
                sku?: string;
                slug?: string;
                brand?: string;
                thumbnail_path?: string;
                image_variants?: {
                  src?: string;
                  url?: string;
                  width?: number;
                }[];
                thumbnail_variants?: {
                  src?: string;
                  url?: string;
                  width?: number;
                }[];
              }[];
              total: number;
              page: number;
              pageSize: number;
            };
          };
        };
      };
    };
    put?: never;
    /** Create a product */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            name: string;
            /** @default  */
            description?: string;
            price: number;
            /** @default 0 */
            discount?: number;
            /** @default false */
            stock?: boolean;
            /** @default  */
            category?: string;
            /** @default  */
            image_path?: string;
            /** @default  */
            image_avif_path?: string;
            /** @default 0 */
            order?: number;
            /** @default false */
            is_archived?: boolean;
            /** @default {} */
            field_last_modified?: {
              [key: string]: {
                ts?: string;
                by?: string;
                rev?: number;
                base_rev?: number;
                changeset_id?: string | null;
              };
            };
            id?: string;
            sku?: string;
            slug?: string;
            brand?: string;
            thumbnail_path?: string;
            image_variants?: {
              src?: string;
              url?: string;
              width?: number;
            }[];
            thumbnail_variants?: {
              src?: string;
              url?: string;
              width?: number;
            }[];
            rev?: number;
          };
        };
      };
      responses: {
        /** @description Created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              command_id: string;
              status: string;
              product: {
                name: string;
                /** @default  */
                description: string;
                price: number;
                /** @default 0 */
                discount: number;
                /** @default false */
                stock: boolean;
                /** @default  */
                category: string;
                /** @default  */
                image_path: string;
                /** @default  */
                image_avif_path: string;
                /** @default 0 */
                order: number;
                /** @default false */
                is_archived: boolean;
                /** @default 0 */
                rev: number;
                /** @default {} */
                field_last_modified: {
                  [key: string]: {
                    ts?: string;
                    by?: string;
                    rev?: number;
                    base_rev?: number;
                    changeset_id?: string | null;
                  };
                };
                id?: string;
                sku?: string;
                slug?: string;
                brand?: string;
                thumbnail_path?: string;
                image_variants?: {
                  src?: string;
                  url?: string;
                  width?: number;
                }[];
                thumbnail_variants?: {
                  src?: string;
                  url?: string;
                  width?: number;
                }[];
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a product by id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              name: string;
              /** @default  */
              description: string;
              price: number;
              /** @default 0 */
              discount: number;
              /** @default false */
              stock: boolean;
              /** @default  */
              category: string;
              /** @default  */
              image_path: string;
              /** @default  */
              image_avif_path: string;
              /** @default 0 */
              order: number;
              /** @default false */
              is_archived: boolean;
              /** @default 0 */
              rev: number;
              /** @default {} */
              field_last_modified: {
                [key: string]: {
                  ts?: string;
                  by?: string;
                  rev?: number;
                  base_rev?: number;
                  changeset_id?: string | null;
                };
              };
              id?: string;
              sku?: string;
              slug?: string;
              brand?: string;
              thumbnail_path?: string;
              image_variants?: {
                src?: string;
                url?: string;
                width?: number;
              }[];
              thumbnail_variants?: {
                src?: string;
                url?: string;
                width?: number;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a product */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a product */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            command_id: string;
            base_revision: number;
            payload: {
              name?: string;
              /** @default  */
              description?: string;
              price?: number;
              /** @default 0 */
              discount?: number;
              /** @default false */
              stock?: boolean;
              /** @default  */
              category?: string;
              /** @default  */
              image_path?: string;
              /** @default  */
              image_avif_path?: string;
              /** @default 0 */
              order?: number;
              /** @default false */
              is_archived?: boolean;
              /** @default 0 */
              rev?: number;
              /** @default {} */
              field_last_modified?: {
                [key: string]: {
                  ts?: string;
                  by?: string;
                  rev?: number;
                  base_rev?: number;
                  changeset_id?: string | null;
                };
              };
              id?: string;
              sku?: string;
              slug?: string;
              brand?: string;
              thumbnail_path?: string;
              image_variants?: {
                src?: string;
                url?: string;
                width?: number;
              }[];
              thumbnail_variants?: {
                src?: string;
                url?: string;
                width?: number;
              }[];
            };
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              command_id: string;
              status: string;
              product: {
                name: string;
                /** @default  */
                description: string;
                price: number;
                /** @default 0 */
                discount: number;
                /** @default false */
                stock: boolean;
                /** @default  */
                category: string;
                /** @default  */
                image_path: string;
                /** @default  */
                image_avif_path: string;
                /** @default 0 */
                order: number;
                /** @default false */
                is_archived: boolean;
                /** @default 0 */
                rev: number;
                /** @default {} */
                field_last_modified: {
                  [key: string]: {
                    ts?: string;
                    by?: string;
                    rev?: number;
                    base_rev?: number;
                    changeset_id?: string | null;
                  };
                };
                id?: string;
                sku?: string;
                slug?: string;
                brand?: string;
                thumbnail_path?: string;
                image_variants?: {
                  src?: string;
                  url?: string;
                  width?: number;
                }[];
                thumbnail_variants?: {
                  src?: string;
                  url?: string;
                  width?: number;
                }[];
              };
            };
          };
        };
        /** @description Error */
        '4XX': {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  '/api/v1/products/bulk/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview a bulk operation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              ok: boolean;
              changes: {
                [key: string]: unknown;
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/bulk/apply': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply a bulk operation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              ok: boolean;
              changed: number;
              changes: {
                [key: string]: unknown;
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder the full catalog */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/batch-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Batch update products in one write */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              command_id: string;
              status: string;
              applied: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List categories */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              rev: number;
              categories: {
                id: string;
                key: string;
                slug: string;
                display_name?: {
                  default?: string;
                };
                nav_group?: string;
                active?: boolean;
                sort_order?: number;
                description?: string;
                subcategories?: {
                  id: string;
                  /** @default  */
                  title: string;
                  /** @default  */
                  product_key: string;
                  /** @default  */
                  slug: string;
                  /** @default  */
                  description: string;
                  /** @default 0 */
                  order: number;
                  /** @default true */
                  enabled: boolean;
                }[];
              }[];
              nav_groups: {
                [key: string]: unknown;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    /** Create a category */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              rev: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a category (optional reassign) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
              reassigned: number;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a category */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              rev: number;
            };
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/categories/batch-update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Batch upsert/delete categories in one write */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              command_id: string;
              status: string;
              applied: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/{id}/subcategories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List subcategories */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            }[];
          };
        };
      };
    };
    put?: never;
    /** Create a subcategory */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/{id}/subcategories/{subId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a subcategory */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a subcategory */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/nav-groups': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List nav groups */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            }[];
          };
        };
      };
    };
    put?: never;
    /** Create a nav group */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/nav-groups/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a nav group */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a nav group */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/storefront/bundles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get storefront bundles */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              bundles: {
                id: string;
                title: string;
                description: string;
                items: {
                  category: string;
                  name: string;
                }[];
                bundlePrice?: number;
              }[];
            };
          };
        };
      };
    };
    /** Save storefront bundles */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
              bundle_count: number;
            };
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/storefront/featured': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get featured sections */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              featuredStaples: {
                [key: string]: unknown;
              }[];
            };
          };
        };
      };
    };
    /** Save featured sections */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/media': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Media inventory */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items: {
                [key: string]: unknown;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/git/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Git status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/git/pull': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Git pull */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              job_id: string;
              status: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/import/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import preview */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/import/apply': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import apply */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export catalog */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              version: string;
              last_updated: string;
              /** @default 0 */
              rev: number;
              /** @default 1 */
              schema_version: number;
              products: {
                name: string;
                /** @default  */
                description: string;
                price: number;
                /** @default 0 */
                discount: number;
                /** @default false */
                stock: boolean;
                /** @default  */
                category: string;
                /** @default  */
                image_path: string;
                /** @default  */
                image_avif_path: string;
                /** @default 0 */
                order: number;
                /** @default false */
                is_archived: boolean;
                /** @default 0 */
                rev: number;
                /** @default {} */
                field_last_modified: {
                  [key: string]: {
                    ts?: string;
                    by?: string;
                    rev?: number;
                    base_rev?: number;
                    changeset_id?: string | null;
                  };
                };
                id?: string;
                sku?: string;
                slug?: string;
                brand?: string;
                thumbnail_path?: string;
                image_variants?: {
                  src?: string;
                  url?: string;
                  width?: number;
                }[];
                thumbnail_variants?: {
                  src?: string;
                  url?: string;
                  width?: number;
                }[];
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/publications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Publications */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            }[];
          };
        };
      };
    };
    put?: never;
    /** Create a publication */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            commitMessage?: string;
            push?: boolean;
            publishAt?: string;
          };
        };
      };
      responses: {
        /** @description Created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              job_id: string;
              status: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/publications/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publication preview */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List pending/running jobs */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              jobs: {
                id: string;
                type: string;
                status: string;
                progress: number;
                started_at?: string;
                completed_at?: string;
                scheduled_at?: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/jobs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a job status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/jobs/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel a job */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/diagnostics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Diagnostics report */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** History entries */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/change-sets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List change sets */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/backup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List backups */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sync/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sync status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/conflicts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List conflicts */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Product: {
      name: string;
      /** @default  */
      description: string;
      price: number;
      /** @default 0 */
      discount: number;
      /** @default false */
      stock: boolean;
      /** @default  */
      category: string;
      /** @default  */
      image_path: string;
      /** @default  */
      image_avif_path: string;
      /** @default 0 */
      order: number;
      /** @default false */
      is_archived: boolean;
      /** @default 0 */
      rev: number;
      /** @default {} */
      field_last_modified: {
        [key: string]: {
          ts?: string;
          by?: string;
          rev?: number;
          base_rev?: number;
          changeset_id?: string | null;
        };
      };
      id?: string;
      sku?: string;
      slug?: string;
      brand?: string;
      thumbnail_path?: string;
      image_variants?: {
        src?: string;
        url?: string;
        width?: number;
      }[];
      thumbnail_variants?: {
        src?: string;
        url?: string;
        width?: number;
      }[];
    };
    ProductCatalog: {
      version: string;
      last_updated: string;
      /** @default 0 */
      rev: number;
      /** @default 1 */
      schema_version: number;
      products: {
        name: string;
        /** @default  */
        description: string;
        price: number;
        /** @default 0 */
        discount: number;
        /** @default false */
        stock: boolean;
        /** @default  */
        category: string;
        /** @default  */
        image_path: string;
        /** @default  */
        image_avif_path: string;
        /** @default 0 */
        order: number;
        /** @default false */
        is_archived: boolean;
        /** @default 0 */
        rev: number;
        /** @default {} */
        field_last_modified: {
          [key: string]: {
            ts?: string;
            by?: string;
            rev?: number;
            base_rev?: number;
            changeset_id?: string | null;
          };
        };
        id?: string;
        sku?: string;
        slug?: string;
        brand?: string;
        thumbnail_path?: string;
        image_variants?: {
          src?: string;
          url?: string;
          width?: number;
        }[];
        thumbnail_variants?: {
          src?: string;
          url?: string;
          width?: number;
        }[];
      }[];
    };
    Category: {
      id: string;
      key: string;
      slug: string;
      display_name?: {
        default?: string;
      };
      nav_group?: string;
      active?: boolean;
      sort_order?: number;
      description?: string;
      subcategories?: {
        id: string;
        /** @default  */
        title: string;
        /** @default  */
        product_key: string;
        /** @default  */
        slug: string;
        /** @default  */
        description: string;
        /** @default 0 */
        order: number;
        /** @default true */
        enabled: boolean;
      }[];
    };
    Bundle: {
      id: string;
      title: string;
      description: string;
      items: {
        category: string;
        name: string;
      }[];
      bundlePrice?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
